import numpy
PI = numpy.pi
GRAVITY = -9.8
REPETITIONS = 1000
AMPLITUDE_BACK_LEG = PI/4
AMPLITUDE_FRONT_LEG = PI/4
FREQUECY_BACK_LEG = 10
FREQUENCY_FRONT_LEG = 10
MAX_SIN = 2*PI
MIN_SIN = 0
PHASE_OFFSET_BACK_LEG = 0
PHASE_OFFSET_FRONT_LEG = 0
MAX_FORCE = 15
SLEEP_TIME = 1/60
